### PR TITLE
Make auto behave like iron-ajax and fire on ready

### PR DESCRIPTION
**Pull request by CodeBaboon**
When using `iron-ajax` setting both the `auto` property to `true` and the `url` property to a value will cause the component to generate a request on `ready`. This PR intends to introduce this behaviour to `d2l-ajax`.

Note that this may cause additional problems related to #32, though I sort of personally think that if a consumer isn't ready for the request to be generated perhaps it shouldn't be using `auto`.

### CODE REVIEW

**Comment by dlockhart** [comment]
Thanks for looking at this @CodeBaboon. I'm a little confused though... how was this ever working? I know it was, because of #32 and because it was causing issues in nav. But I don't know how it _could_ have been working since the `auto` property isn't getting passed down to `iron-ajax`...

**Comment by CodeBaboon** [comment]
@dlockhart I think it works so long as you modify one of the `url`, `params`, or `body` properties at some point after [this observer](https://github.com/BrightspaceUI/ajax/blob/master/d2l-ajax.html#L88) is wired up. I can't speak to the specific timing that issue #32 addresses, though.

**Comment by ryantmer** [comment]
Side note: make sure to run `npm run build` and commit the result as well, as it creates the minified `d2l-ajax-framed` :)

**Comment by dlockhart** [comment]
Aha, I know what's making it work today -- [this line](https://code.facebook.com/posts/557147474482256). You may want to remove that line to avoid generating the request twice?

**Comment by CodeBaboon** [comment]
But that line is necessary for the request to fire on any subsequent change, which is what `auto` is designed for. And if it is firing on ready and then being switched and you don't want it to fire again then `auto` isn't the right thing for that scenario.

**Comment by CodeBaboon** [comment]
@ryantmer I squash-pushed an update to the minified file, thanks for the tip.

**Comment by ryantmer** [comment]
Looking at how `iron-ajax` is doing things, they've got a slightly different setup - they're using a debounce in conjunction with watching `auto` in the same observer as everything else. It's also got a default value - maybe we can do the same here?

I removed the observing on `auto` in https://github.com/BrightspaceUI/ajax/pull/29, but it seems like perhaps that was an over-optimization - maybe adding it back in would be (part of) the solution?

**Comment by CodeBaboon** [comment]
@ryantmer Just adding `auto` back into the observed properties seems to fix it for my usage. I've modified this PR to reflect that. Will that still screw up the nav situations from #32?

**Comment by ryantmer** [comment]
Seems... okay? I think? 😕 

The observer won't fire until after ready I'm fairly sure, and in fact only after all observed values have been initially set, so I think that would solve the "request being fired before `ready`" problem. Maybe `auto` should have a `value` initially as well - iron-ajax does set one. Not sure if it's required granted...

**Comment by CodeBaboon** [comment]
@ryantmer, @dlockhart helped me set up the navbar scenario for testing with this modified code and it appears to still work correctly with the changes.

**Comment by ryantmer** [comment]
Nice! Seems like I introduced some risk with those perf changes, and this removes some of that risk (by risk I mean brokenness 😜).

**Comment by ryantmer** [comment]
Follow-up: Sauce doesn't work on forks :(

**Comment by CodeBaboon** [comment]
K, I'm closing this PR and I'll open one against a branch local to this repo.

**Pull request closed without merging**
