### PR TITLE
Update the bindings to iron-ajax to be hyphenated instead of camel ca…

### PR DESCRIPTION
**Pull request by davewagler-d2l**
…se so that they properly bind.

### CODE REVIEW

**Comment by dlockhart** [comment]
CI is failing because this repo isn't set up to run Sauce from a fork.

**Comment by dlockhart** [comment]
Wow... looks like this was behaving like this since the initial commit, how did we never notice?! I've [created an issue](https://github.com/BrightspaceUI/ajax/issues/36) to add tests to cover this in the future.

**Comment by dlockhart** [comment]
@davewagler-d2l I've just fixed up the Sauce credentials so that they work from forks. Could you rebase those changes into your fork? That should run CI again and hopefully it'll pass this time.

**Comment by dlockhart** [comment]
Added tests to cover this behaviour in #40, will merge once this merges.

**Comment by davewagler-d2l** [comment]
Just pulled in our changes - hopefully this will pass now.

**Comment by dlockhart** [comment]
Looks good -- thanks @davewagler-d2l for the contrib. I'll merge, add my tests and do a release.

**Pull request merged**
