### PR TITLE
stopPropagation to prevent events from firing twice

### PR DESCRIPTION
**Pull request by ryantmer**
The request/response events were being fired twice to anybody listening outside of a d2l-ajax element, as the event coming from the inner iron-ajax wasn't being stopped. Now, only one event is fired, as one would expect.

### CODE REVIEW

**Comment by ryantmer** [comment]
Pretty sure this makes sense - found this while playing around with some changes to `d2l-search-widget`, I was getting multiple being generated by it, which turned out to be because `d2l-ajax` was emitting two `iron-ajax-response` events. Seems like this fixes it, to only emit the second one.

**Comment by omsmith** [comment]
Is there a point to refiring it? just want the updated `e.target` or something like that?

**Comment by ryantmer** [comment]
Yeah =/ Not even entirely sure that we need it, but it would be a breaking change otherwise.

**Comment by omsmith** [comment]
Is the same not true of `onError`?

**Comment by ryantmer** [comment]
That one I can't figure out - calling `stopPropagation` on it causes issues in tests... haven't been able to figure out if that's a test thing, or if `iron-ajax-error` is different (seems like the former?).

**Comment by ryantmer** [comment]
Yeah, looks like it's a test thing. Bah. The `e` being passed is a normal `Event` under normal operation, but in the test it is not.

**Comment by ryantmer** [comment]
Ah, the problem was around `_getCachedAuthToken` - that can generate a normal Error (rather than an Event), but also gets sent through `onError` via the promise chain. That won't propagate anyway, so simple fix: check if we can `stopPropagation` before trying to do it.

**Pull request merged**
