### PR TITLE
Update readme with soft-deprecation notice

### PR DESCRIPTION
**Pull request by ryantmer**
Most use cases where we were using this repo have now been switched to use `d2l-fetch` instead, and we generally want to prevent new usages of this component.

### CODE REVIEW

**Comment by dlockhart** [comment]
Amazing, thanks for adding this -- I was just going to suggest it!

**Comment by ryantmer** [comment]
@CodeBaboon Hmmmm fair point. There are still a few repos of ours that reference this, but at least two of them are themselves deprecated, so not really concern there - I can look into the other as well though, to see how even-more-largely we can deprecate this.

**Comment by dlockhart** [comment]
I agree with @CodeBaboon that we could use stronger language here. `d2l-fetch` has so many advantages over `d2l-ajax`... I'm not seeing a compelling case for leaving the door open to use it.

**Comment by ryantmer** [comment]
Looks like two are fully deprecated, one or two usages are on repos that have recent-ish updates, and the rest are fairly old ones (>1 year since last commit), so I'll update the wording here to a harder deprecation notice. (And perhaps open issues on the recent-ish repos recommending they switch over.)

**Comment by ryantmer** [comment]
Once this is merged, I'd also like to recommend we archive this repo - it makes everything read-only, and puts a nice banner at the top indicating that it's archived. (It can also be un-archived should changes need to be made at some point.)

**Pull request merged**
